"""Adding Pokemon

Revision ID: 2f12ede66881
Revises: 69cb410ba6c6
Create Date: 2023-01-31 14:58:14.197127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f12ede66881'
down_revision = '69cb410ba6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('ability', sa.String(length=45), nullable=False),
    sa.Column('base_xp', sa.Integer(), nullable=False),
    sa.Column('front_shiny', sa.String(length=145), nullable=False),
    sa.Column('base_atk', sa.Integer(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_def', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
